Doc tweak: use a number for which nominative and genitive forms are distinct
unicode-org/cldr pull request #1035
Opened 2021-02-15 22:22 UTC by hugovdm

No ticket yet: does this need a ticket on its own, or can it fit into a "misc improvements" ticket?

Rationale: to make the example clear, we need a plural falling in the "few" or "one" categories, since these have distinctions between "nominative" and "genitive". The plural rule for "few" looks as follows:

```
    few{
        "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 3"
        "2~34, 42~44, 52~54, 62, 102, 1002, …"
    }
```

33% seems like a more reasonable number than 2%, based on my lights for example - but 1% could also work.

The data for "percent" for "ru" shows no distinction between nominative and genitive for the "many" and "other" plural categories:

```
    genitive{
        few{"{0} процентов"}
        many{"{0} процентов"}
        one{"{0} процента"}
        other{"{0} процента"}
    }
```

Data for ru nominative:

```
    few{"{0} процента"}
    many{"{0} процентов"}
    one{"{0} процент"}
    other{"{0} процента"}
```

##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-_____
- [ ] Updated PR title and link in previous line to include Issue number

2021-10-05 17:39 UTC, macchiati approved these changes

2021-10-05 17:39 UTC, macchiati requested changes
Looks reasonable, but needs to be filed against maint-40 instead of 39.

2022-01-05 17:31 UTC, hugovdm commented
Pardon some messiness in this PR: because the commit was 10 months old, I did a rebase onto the upstream/main branch, and force-pushed. (Two force-pushes in fact, because I first went for upstream/master.)

2022-02-02 18:27 UTC, macchiati approved these changes

2022-02-02 18:27 UTC, merged