CLDR-14589 change maori spelling
unicode-org/cldr pull request #1123
Opened 2021-03-19 19:41 UTC by stenshamn

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14589
- [X] Updated PR title and link in previous line to include Issue number

2021-03-19 19:42 UTC, stenshamn commented
There were _a lot_ more instances to change than I first thought. Please ensure I didn't break anything...

2021-03-19 20:28 UTC, macchiati requested changes

2021-03-19 20:28 UTC, macchiati commented on common/supplemental/languageInfo.xml
> +			<languageMatch desired="mi"	supported="en"	distance="20"	oneway="true"/>	<!-- Māori: mi ⇒ en -->
Cases like these in comments won't matter (and will typically be regenerated when the tools are run later on).

But they don't hurt either.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/draft/keyboard/osx/osx-locales.csv
> +Māori,mi,
Retract, probably want to leave the keyboard ones alone, since they are reflecting what the source data had.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/icu/idList.txt
> +language; mi; Māori; 2004-07-06; ;
Not quite sure what this is, but should retract for safety.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO-639-2_values_8bits.txt
> +mao|mri|mi|Māori|maori
Retract the ones in data, since they represent some external source file.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
> +#Google	;	mi	;	basic	;	Māori
This one's ok to keep.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/WikipediaOfficialLanguages.txt
> +Māori (statewide)
Retract the ones in data, since they represent some external source file.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt
> +New Zealand	NZ	"4,545,627"	99%	"189,000,000,000"	official	Māori	mi	"129,000"			"http://www.ethnologue.com/show_language.asp?code=mri 70,000 in 1991, 100,000 who understand it, but do not speak it ; e
Ok to keep (effectively a comment)

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/alternate_language_names.txt
> +mi  ;   Māori
Retract, used to deal with external data.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/iso-639-3.tab
> +mri	mao	mri	mi	I	L	Māori
Retract, external data.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/iso-639-3_Name_Index.tab
> +mri	Māori	Māori
Retract this file, external data.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language-subtag-registry
> +Description: Māori
Retract this file, external data.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script_raw.txt
> -mi	Maori	primary	Latn	Latin
OK to keep.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/test/resources/org/unicode/cldr/unittest/data/xmb/en.xml
> +		desc='The name of the language with BCP47 language code = mi. For more information, see http://cldr.org/translation/language-names.'>Māori</msg>
OK to keep

2021-03-19 20:28 UTC, macchiati commented on keyboards/osx/mi-t-k0-osx.xml
> +		<name value="Māori"/>
Retract, probably want to leave the keyboard ones alone, since they are reflecting what the source data had.

2021-03-19 20:28 UTC, macchiati commented on keyboards/windows/mi-t-k0-windows.xml
> +		<name value="Māori"/>
Retract, probably want to leave the keyboard ones alone, since they are reflecting what the source data had.

2021-03-19 20:28 UTC, macchiati commented on tools/cldr-code/src/main/java/org/unicode/cldr/tool/IdToPath.java
> +            { "3083634935683991293", "//ldml/localeDisplayNames/languages/language[@type=\"mi\"]", "Māori" },
Not sure about this one, so best to retract.

2021-03-19 21:01 UTC, stenshamn commented
Added a second commit to remove some of the changes. @macchiati , would you mind checking again?

2021-03-19 21:06 UTC, stenshamn commented
Ugh, missed three. For sure now...

2021-03-19 21:17 UTC, macchiati approved these changes

2021-03-19 21:36 UTC, stenshamn commented
@macchiati , your approval evaporated after I squashed.

2021-03-19 21:49 UTC, macchiati approved these changes

2021-03-19 21:50 UTC, macchiati commented
Yes, that's why I use the "Squash and merge" button...

2021-03-25 17:00 UTC, srl295 approved these changes
lgtm

2021-03-31 15:33 UTC, merged