CLDR-14662 fixes to Coverage menu
unicode-org/cldr pull request #1214
Opened 2021-04-27 22:39 UTC by srl295

CLDR-14662

- rename Auto to Default
- org coverage is really per locale, store it this way in the APIs
- move the default labelling into the vue code
- add a $forceReload() in MainHeader if the menus change
workaround for a lack of reactivity

- [X] yea, i think this fixes the issue!

2021-04-27 22:40 UTC, srl295 commented on tools/cldr-apps/js/src/views/MainHeader.vue
> +      }
workaround

2021-04-27 22:40 UTC, srl295 commented on tools/cldr-apps/js/src/views/MainHeader.vue
> -import * as cldrSurvey from "../esm/cldrSurvey.js";
unused

2021-04-27 22:40 UTC, srl295 commented on tools/cldr-apps/js/src/views/MainHeader.vue
> +          <option :key="n" v-for="n in voteCountMenu">{{ n }}</option>
fixes a warning

2021-04-28 00:00 UTC, btangmu commented on tools/cldr-apps/js/src/esm/cldrMenu.js
>      value: "auto",
needs prettier

2021-04-28 00:02 UTC, btangmu requested changes
looks good but needs formatting

2021-04-28 15:14 UTC, btangmu approved these changes

2021-04-28 15:16 UTC, merged