CLDR-14286 Fix Interval format GyMMM for locale fa
unicode-org/cldr pull request #1410
Opened 2021-08-10 19:33 UTC by kipcole9

The pattern for `<greatestDifference id="M">` has no repeating pattern
when TR35 indicates:

  The pattern is then designed to be broken up into two pieces by
  determining the first repeating field. For example, "MMM d-d, y"
  would be broken up into "MMM d-" and "d, y".

This PR replaces:

  <greatestDifference id="M">LLL تا MMM y G</greatestDifference>

with

  <greatestDifference id="M">MMM تا MMM y G</greatestDifference>

replacing LLL (standalone month) with MMM (month) thereby ensuring
there is a repeating pattern per the specification.

CLDR-_____

- [ ] This PR completes the ticket.

2021-08-10 21:57 UTC, srl295 commented
@kipcole9 errs probably unrelated

2021-08-11 07:50 UTC, pedberg-icu approved these changes

2021-08-11 07:54 UTC, roozbehp commented
Please don't merge. This is wrong.

2021-08-11 07:57 UTC, roozbehp requested changes
Since LLL and MMM values are different for some Persian month names, this would result in grammatically incorrect ranges.

There bug should be fixed in the spec or the code that parses this data. The data itself is correct.

2021-08-11 07:59 UTC, roozbehp commented
To clarify, the rule for Persian MMM/MMMM vs LLL/LLLL is that if a year immediately follows the month name, the format version is used, otherwise the standalone version is used.

2021-08-11 08:41 UTC, kipcole9 commented
One approach might be to say that for the purposes of determining “repeating field”, that “standalone” and “normal” formats are equivalent. In this example, treat `L === M` when finding the break point of the interval pattern.

2021-08-11 15:23 UTC, srl295 commented
@pedberg-icu i added an 'agenda' label to the ticket if it needs discussion

2021-08-12 03:31 UTC, pedberg-icu commented
> One approach might be to say that for the purposes of determining “repeating field”, that “standalone” and “format” formats are equivalent. In this example, treat `L === M` when finding the break point of the interval pattern.

@kipcole9 I like that approach. Please start a new PR for that and close this PR.

2021-08-12 03:35 UTC, closed without merging