CLDR-14332 correct link
unicode-org/cldr pull request #1545
Opened 2021-10-19 07:25 UTC by FrankYFTang

CLDR-14332

- [ ] This PR completes the ticket.

2021-11-17 04:18 UTC, macchiati approved these changes

2021-11-17 04:42 UTC, AEApple commented
@srl295 - Associated this fix with the ticket currently assigned to you since it seems like the closest.

2021-11-17 13:31 UTC, srl295 requested changes
What is the intention?

2021-11-17 13:31 UTC, srl295 commented on docs/README.md
> +- [Unicode Technical Standard #35 UNICODE LOCALE DATA MARKUP LANGUAGE (LDML)](https://unicode-org.github.io/cldr/ldml/tr35.html)
```suggestion
- [Unicode Technical Standard #35 UNICODE LOCALE DATA MARKUP LANGUAGE (LDML)](ldml/tr35.md)
```

I don't think we should make this change. This should be a relative link. It's a html link as a compromise until #1572 lands.

2021-11-17 14:36 UTC, macchiati commented
Ok, let's close

On Wed, Nov 17, 2021, 05:31 Steven R. Loomis ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> What is the intention?
> ------------------------------
>
> In docs/README.md
> <https://github.com/unicode-org/cldr/pull/1545#discussion_r751242136>:
>
> > @@ -4,7 +4,7 @@ CLDR main page: [https://unicode.org/cldr](unicode.org/cldr)
>
>
>
>  ## TR35
>
>
>
> -- [Unicode Technical Standard #35 UNICODE LOCALE DATA MARKUP LANGUAGE (LDML)](ldml/tr35.html)
>
> +- [Unicode Technical Standard #35 UNICODE LOCALE DATA MARKUP LANGUAGE (LDML)](https://unicode-org.github.io/cldr/ldml/tr35.html)
>
>
> ⬇️ Suggested change
>
> -- [Unicode Technical Standard #35 UNICODE LOCALE DATA MARKUP LANGUAGE (LDML)](https://unicode-org.github.io/cldr/ldml/tr35.html)
>
> +- [Unicode Technical Standard #35 UNICODE LOCALE DATA MARKUP LANGUAGE (LDML)](ldml/tr35.md)
>
>
> I don't think we should make this change. This should be a relative link.
> It's a html link as a compromise until #1572
> <https://github.com/unicode-org/cldr/pull/1572> lands.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/cldr/pull/1545#pullrequestreview-808588808>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLEMAZCCEHVLPFJPVEYALUMOVDHANCNFSM5GINC6KA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-02-02 17:22 UTC, srl295 commented
no reply, closing

2022-02-02 17:22 UTC, closed without merging