Replace FixedDecimal with DecimalQuantity for pllural rule samples
unicode-org/cldr pull request #1800
Opened 2022-03-16 15:54 UTC by echeran

CLDR-_____

- [ ] This PR completes the ticket.

Instructions to reproduce:

1. Switch to your working copy of ICU, and then...
2. Checkout the [PR #2007](https://github.com/unicode-org/icu/pull/2007) that does the ICU side of work. You can use the [Github CLI tool](https://cli.github.com/) to do this with the command `gh pr checkout 2007`
3. Build the ICU4J jar that also includes CLDR-specific dependencies: `cd icu4j`;  `ant clean`; `ant -noinput releaseCLDR -f build.xml`
4. Give that new jar file a unique testing-specific version number and register ("install") it to your local file system's Maven cache of artifacts (jar files).  For a version string `71.0.1-SNAPSHOT-icu-pr-2007`, we would install it with the proper Maven groupId, artifactId coordinates as:  `mvn install:install-file -Durl=file:repo -DgroupId=com.ibm.icu -DartifactId=icu4j-for-cldr -Dversion=71.0.1-SNAPSHOT-icu-pr-2007 -Dpackaging=jar -Dfile=icu4j.jar -Dsources=icu4j-src.jar`
5. Switch to your working copy of CLDR, and then...
6. Checkout this PR.  Ex: `gh pr checkout 1800`
7. Edit the file `tools/pom.xml`, so that in the `<dependency>` entry for `<artifactId>icu4j-for-cldr</artifactId>`, update the version so that it reads as `<version>71.0.1-SNAPSHOT-icu-pr-2007</version>`
8. Run tests via `mvn test --file=tools/pom.xml`

2022-03-16 17:18 UTC, macchiati requested changes
Before this goes in, the plural data file should be regenerated to verify that none of the samples change because of this.

2022-03-16 20:20 UTC, echeran commented
note to self: these are the CLDR instructions for regenerating the plural data: https://cldr.unicode.org/development/updating-codes/addingfixing-plural-and-ordinals

2022-03-18 00:52 UTC, echeran commented
@srl295 I finished off the checklist you presented, after first making more code changes to address the remaining test failures. 

Tests pass now, but of course, they need to be run against the pending change to ICU, so you can only do that locally.  I am following the steps that I listed above in the PR description to reproduce that proper CLDR-ICU dependency during tests with in-flight development in both places. I believe those testing steps to be correct, but please lmk if you disagree.

I continue to re-run this PR's tests after any changes to the "upstream" ICU PR https://github.com/unicode-org/icu/pull/2007.

@macchiati I ran the instructions you provided to update the plural rules and included the diffs in this PR.

Also, the diffs from the auto-generated output included updates to the file header, which updates the things like the year in the copyright notice. I included that as well in this PR -- is that what you all prefer?

I see that the Jira ticket is not accepted. What is the process for that, could that be handled in the next weekly TC meeting?

Ultimately, though, I recognize this PR can't be merged as-is right now.  Instead, only after the ICU PR is merged and a new snapshot is created for icu4j-for-cldr, then the next time that @pedberg-icu or someone updates that snapshot version in CLDR, that version update will want to be combined with these corresponding code changes.  But since the ICU PR won't make be included for the 71 release, we will have to wait until we're ready for new v72 changes to begin the process.

2022-03-20 00:05 UTC, macchiati commented on common/supplemental/pluralRanges.xml
> +			<pluralRange start="one"   end="one"   result="one"/>
We'll need to check this see if there are difference for the 'many' case.

2022-03-20 00:10 UTC, macchiati reviewed
Changes look good. I didn't see any changes in the samples in the rule files, which is great.

2022-03-20 00:11 UTC, macchiati commented
I put the PR on the agenda for Monday. I have no doubt that it will be accepted.

Agreed that we can't merge this until the version of ICU it depends on is merged in.

2022-08-11 03:10 UTC, macchiati approved these changes

2022-08-11 03:10 UTC, macchiati commented
Looks good except for the failing tests.

2022-08-11 23:23 UTC, markusicu approved these changes
lgtm

2022-08-12 00:00 UTC, merged