CLDR-15637 update sampleName surname-core
unicode-org/cldr pull request #2005
Opened 2022-05-13 21:02 UTC by mimckenna

CLDR-15637

- [ ] This PR does NOT complete the ticket.

Update en.xml personNames/sampleName with matching surname and surname-core.

2022-05-13 21:27 UTC, macchiati requested changes
The problem is that the surname has to equal surname-prefix + " " + surname-core.

Your change has:

Meyer Wolf == van den + Meyer Wolf

which is false. 

Change to:
surname: van den Wolf
surname-core: Wolf
Then we will have:

van den Wolf == van den + Wolf

2022-05-15 07:03 UTC, mimckenna commented
I'm updating the surname to equal prefix + core, but the remainder check logic allows surname to equal core without the prefix, such as 
```
{ surname: "Wolf", surname-prefix: "van den", surname-core: "Wolf" }
```

from test at: https://jsfiddle.net/mimckenna/oyq1sdap/42/
![image](https://user-images.githubusercontent.com/11297262/168460833-75385376-7049-4c56-9cf2-195fa9098bae.png)
 
Also, Malaysian will have name where the surname may be independent of a surname-prefix (see: https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/s42/mysEn.pdf)

Example: ms_MY: `{ prefix:"Puasn",  given:"Aisyah", surname-prefix:"binti Haji", surname:"Musa" }`
![image](https://user-images.githubusercontent.com/11297262/168461145-c073ca75-dd9e-4ccc-9332-1993b354debd.png)

Malaysian _could_ be represented with only surname-prefix and surname-core, but it would be incorrect to assume that surname on its own would always be composed of surname-prefix and surname-core that way it is in Dutch.

2022-05-15 13:41 UTC, macchiati approved these changes

2022-05-15 14:08 UTC, merged

2022-05-15 14:08 UTC, macchiati commented
Let's discuss this via email