CLDR-15801 add missing islamic calendar items, using CldrModify
unicode-org/cldr pull request #2251
Opened 2022-08-04 22:24 UTC by macchiati

CLDR-15801

- [ ] This PR completes the ticket.

2022-08-04 23:31 UTC, macchiati commented
Can one of you review this?

2022-08-04 23:58 UTC, macchiati commented
Just fixed the 3 lines causing a failure

2022-08-05 00:03 UTC, pedberg-icu requested changes
Looks good with the second fix

2022-08-05 00:03 UTC, pedberg-icu approved these changes

2022-08-05 01:58 UTC, merged