CLDR-15924 Fix ta and si person names
unicode-org/cldr pull request #2297
Opened 2022-08-18 03:49 UTC by macchiati

CLDR-15924

- [ ] This PR completes the ticket.

2022-08-18 17:09 UTC, pedberg-icu submitted a review, later dismissed

2022-08-18 19:53 UTC, macchiati commented
Just had to resolve merge conflicts. Should be ok once the tests finish.

2022-08-18 21:38 UTC, mimckenna requested changes
A few requested changes 
- be sure both 'si' and 'ta' added to surnameFirst list.
- add `{prefix}` to long, referring, formal

2022-08-18 21:38 UTC, mimckenna commented on common/main/si.xml
>  			<namePattern>{surname} {given-informal}</namePattern>
this is for a few lines up.
In Sinhala, we should add _prefix_ in long, referring, formal
```
		<personName order="surnameFirst" length="long" usage="referring" formality="formal">
			<namePattern>{prefix} {surname} {given} {given2} {suffix}</namePattern>
		</personName>
```
see: https://cmb.ac.lk/honorary-degrees/ - si_Latn - formal presentation
https://www.parliament.lk/uploads/documents/paperspresented/annual-report-university-of-jaffna-2017-si.pdf - list of faculty

2022-08-18 21:38 UTC, mimckenna commented on common/main/si.xml
> +		<nameOrderLocales order="surnameFirst">ko si te vi yue zh</nameOrderLocales>
Add 'ta' to _surnameFirst_ list
```
<nameOrderLocales order="surnameFirst">ko si ta te vi yue zh</nameOrderLocales>
```

2022-08-18 23:16 UTC, macchiati commented
I'd like to get this merged, then follow up with another PR with fixes for Mike's comments. @pedberg-icu can you stamp it?

2022-08-18 23:18 UTC, pedberg-icu approved these changes

2022-08-18 23:18 UTC, merged

2022-08-19 15:58 UTC, mimckenna commented
Looks OK for release - we can patch later if Tamil and Sri Lankan folks want `{prefix}` for referring, formal.