CLDR-15414 json: personnames, unit fixes
unicode-org/cldr pull request #2342
Opened 2022-09-07 22:27 UTC by srl295

- fix for units in CLDR-14421
- fix for supplemental person names data in CLDR-15414
- rename package to cldr-person-names* instead of cldr-personNames*

CLDR-15414

- [ ] This PR completes the ticket.

2022-09-07 22:28 UTC, srl295 commented
You can view the effect of this PR here: https://github.com/unicode-org/cldr-json/pull/42/commits/3e32798830ef3c92e044fc485d6cc0b8f3aca444

2022-09-07 22:29 UTC, srl295 commented on tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
> +section=unitIdComponents ; path=//cldr/supplemental/unitIdComponents/.* ; package=core
these unitIdComponents didn't previously have a package to go to

2022-09-07 22:29 UTC, srl295 commented on tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
> +section=personNamesDefaults ; path=//cldr/supplemental/personNamesDefaults/.* ; package=core
these go in cldr-core as supplemental.

2022-09-07 23:24 UTC, macchiati approved these changes

2022-09-08 16:26 UTC, merged

2022-12-17 10:57 UTC, Mannyflow7 requested changes
c05e58021c85dd56ddd74cf1116275bf65b6f036