CLDR-16161 fix CSS for PersonName (and possibly others)
unicode-org/cldr pull request #2570
Opened 2022-11-23 18:40 UTC by srl295

CLDR-16161

- update ChartPersonName.java to put a <div class="ReportChart"> around
its output
- create a new reports.css file in org.unicode.cldr.tool (so it could be used by the Chart.java tooling)
 This is based on the sibling index.css file but has .ReportChart around each declaration.
- include that reports.css file directly into the webpack bundle by updating index.js

Note that .dtf-table and related styles were already in surveytool.css so I moved those
into reports.css

- [ ] This PR completes the ticket.

![image](https://user-images.githubusercontent.com/855219/203622583-9f7008e4-68d9-4093-8f6f-d458c77953b6.png)

2022-11-23 18:48 UTC, srl295 commented
Huh, also I noticed that for Burmese for example the chart generation just quits. I added a note, `No sample names to display.` so users would at least see something.

Not sure how this affects chart mode.

2022-11-23 19:16 UTC, macchiati commented
I looked at the my.xml data, and it is pretty broken; all inheriting from
Root, which is useless. I'll add a warning in the ChartPersonName.

On Wed, Nov 23, 2022 at 10:48 AM Steven R. Loomis ***@***.***>
wrote:

> Huh, also I noticed that for Burmese for example the chart generation just
> quits. I added a note, No sample names to display. so users would at
> least see something.
>
> Not sure how this affects chart mode.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/cldr/pull/2570#issuecomment-1325519331>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLEMEXQFEAKJ4GFNKUAXDWJZRJRANCNFSM6AAAAAASJITFDE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-11-23 19:24 UTC, srl295 commented
> I looked at the my.xml data, and it is pretty broken; all inheriting from Root, which is useless. I'll add a warning in the ChartPersonName.
> […](#)

I added one in https://github.com/unicode-org/cldr/pull/2570/files#diff-c7152ca988146192e0d7872d062c51d74ba319ef8dfd0bb2f6a616e5e56b8810R74

The report already exits if there's no data, but that isn't as helpful within the surveytool.

2022-11-23 22:52 UTC, macchiati requested changes

2022-11-24 00:19 UTC, srl295 commented on tools/cldr-code/src/main/resources/org/unicode/cldr/tool/reports.css
> +/*
The problem here is that index.css redefine `td`, `th` and other top level elements, without any scope. That's kind of drastic.


Coudn't we change the chart template to something like

```html
 <div class="ChartReport">
    %body%
 </div>
```

Should be harmless to charts that aren't using those classes.

2022-11-24 00:23 UTC, srl295 commented on tools/cldr-code/src/main/resources/org/unicode/cldr/tool/reports.css
> +/*
```diff
diff --git a/tools/cldr-code/src/main/resources/org/unicode/cldr/tool/chart-template.html b/tools/cldr-code/src/main/resources/org/unicode/cldr/tool/chart-template.html
index d2bae0af0b..26863251da 100644
--- a/tools/cldr-code/src/main/resources/org/unicode/cldr/tool/chart-template.html
+++ b/tools/cldr-code/src/main/resources/org/unicode/cldr/tool/chart-template.html
@@ -7,6 +7,7 @@
 <link rel="stylesheet" type="text/css"
        href="https://www.unicode.org/webscripts/standard_styles.css">
 <link rel="stylesheet" type="text/css" href="index.css">
+<link rel="stylesheet" type="text/css" href="reports.css">
 %header%
 </head>
 
@@ -33,7 +34,7 @@
                        <td colspan="2" class="gray">&nbsp;</td>
                </tr>
        </table>
-       <div class="body">
+       <div class="body ReportChart">
                <div align="center">
                        <table style="width:100%">
                                <tr>
@@ -74,4 +75,4 @@
        </div>
 </body>
 
-</html>
\ No newline at end of file
```

… plus adding reports.css to the filecopier

in any event, this PR does fix the style even though it makes a copy of the CSS.  

Also the reports/Charts are already at odds with SurveyTool due to not setting lang= etc.  Filed https://unicode-org.atlassian.net/browse/CLDR-16165

2022-11-26 00:31 UTC, srl295 commented on tools/cldr-code/src/main/resources/org/unicode/cldr/tool/reports.css
> +/*
If it's important for this release, I wonder if we could accept this PR as is, with the duplication, and come back to this later, even early next year… I'm running low on November, and I know that this PR works

2022-11-26 04:14 UTC, macchiati approved these changes

2022-11-26 04:14 UTC, macchiati commented
Ok, let's do that. Please file a ticket to complete the work.

(I was hoping their might be some CSS magic...)


On Fri, Nov 25, 2022 at 4:32 PM Steven R. Loomis ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tools/cldr-code/src/main/resources/org/unicode/cldr/tool/reports.css
> <https://github.com/unicode-org/cldr/pull/2570#discussion_r1032716737>:
>
> > @@ -0,0 +1,236 @@
>
> +/*
>
>
> If it's important for this release, I wonder if we could accept this PR as
> is, with the duplication, and come back to this later, even early next
> year… I'm running low on November, and I know that this PR works
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/cldr/pull/2570#discussion_r1032716737>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLEMAOYQ373PUVMIOW2TDWKFK77ANCNFSM6AAAAAASJITFDE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-11-26 05:27 UTC, srl295 commented
> Ok, let's do that. Please file a ticket to complete the work.
> 
> (I was hoping their might be some CSS magic...)

Not that I know of. 

Will do before this ticket is closed.

2022-11-26 05:28 UTC, merged