CLDR-15034 kbd: add @UESCAPED DTD annotation
unicode-org/cldr pull request #2642
Opened 2023-01-05 18:45 UTC by srl295

_(Note: Keyboard PR- not for v43!)_

CLDR-15034

Add a `` DTD annotation noting where `\u{…}` escaping is allowed on an attribute.
This does not address changes to UnicodeSet escaping, because there are still open issues around UnicodeSets in keyboard

2023-01-05 19:52 UTC, macchiati requested changes
I think we need more information about the impact of this statement. If the attribute foo has it:

- if the rawValue is \u{61}b, then the resolved value is 'ab', right?
- if we read the values, eg with CLDRFile, is the software expected to resolve the value?
- if we write the values, eg with CLDRFile, which characters are expected to be escaped?

Some of these are gaps in the original explanation of \u in keyboards, but we should take the time to nail it down.

2023-01-05 19:58 UTC, srl295 commented
> I think we need more information about the impact of this statement. If the attribute foo has it:
> 
> 
> 
> - if the rawValue is \u{61}b, then the resolved value is 'ab', right?

Yes 

> - if we read the values, eg with CLDRFile, is the software expected to resolve the value?
> 
> - if we write the values, eg with CLDRFile, which characters are expected to be escaped?

Right now these are only on keyboard attributes. I don't make any statement here about CLDRFile but potentially it could do as you say, with some unicode set that defines what needs to be escaped. 



> 
> 
> Some of these are gaps in the original explanation of \u in keyboards, but we should take the time to nail it down.

Right. Currently the spec for \u is prose on certain elements and this makes it metadata. 

An alternate approach would be to use a VALUE subtype indicating that escaping is acceptable.   VALUE any/escaped perhaps.

2023-01-06 00:00 UTC, macchiati commented
Hmmm. It doesn't quite fit the VALUE use case. But maybe if we changed the name for clarity, eg @ALLOWS_UESC, to indicate that the attribute value allows \u syntax (but doesn't require it)?

2023-01-07 00:21 UTC, mcdurdin reviewed
I concur with the `@ALLOWS_UESC` rename -- otherwise afaict the changes are correct.

2023-01-17 01:09 UTC, macchiati requested changes

2023-01-17 01:09 UTC, macchiati commented on docs/ldml/tr35-keyboards.md
> +Attributes escaped in this manner are annotated with the `<!--@ALLOWS_UESC-->` DTD annotation, see [DTD Annotations](tr35.md#57-dtd-annotations)
Attribute => Attribute values

2023-01-17 01:09 UTC, macchiati commented on docs/ldml/tr35-keyboards.md
> +Attributes escaped in this manner are annotated with the `<!--@ALLOWS_UESC-->` DTD annotation, see [DTD Annotations](tr35.md#57-dtd-annotations)
Multiple places below.

2023-01-17 01:49 UTC, srl295 commented on docs/ldml/tr35-keyboards.md
> +Attributes escaped in this manner are annotated with the `<!--@ALLOWS_UESC-->` DTD annotation, see [DTD Annotations](tr35.md#57-dtd-annotations)
good catch, thanks

2023-02-02 01:26 UTC, macchiati approved these changes

2023-02-17 20:19 UTC, merged