CLDR-16417 Add spec text for era codes
unicode-org/cldr pull request #2745
Opened 2023-02-22 23:41 UTC by sffc

CLDR-16417

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2023-02-23 03:47 UTC, pedberg-icu approved these changes
looks good, thanks

2023-02-23 19:29 UTC, macchiati requested changes

2023-02-23 19:29 UTC, macchiati commented on docs/ldml/tr35-dates.md
> +3. If the same era code is used in multiple calendars, the arithmetic for that era must be the same in all calendars in which it is used. For example, the `ethioaa` era is used in two calendar system
the arithmetic => 
the calculations for year, month, and day

2023-02-23 21:40 UTC, macchiati approved these changes

2023-02-23 22:37 UTC, pedberg-icu approved these changes

2023-02-23 23:02 UTC, merged

2023-03-15 00:02 UTC, srl295 commented
no discussion of -1 and -2 eras