CLDR-16560 Requirements for storing inheritance marker
unicode-org/cldr pull request #2889
Opened 2023-05-03 15:09 UTC by btangmu

-Change VoteResolver.DROP_HARD_INHERITANCE to true

-When needed to meet requirements, change INHERITANCE_MARKER to Bailey or vice-versa

-New method STFactory.PerLocaleData.reviseInheritanceAsNeeded called by setValueFromResolver

-New method VoteResolver.reviseInheritanceAsNeeded called by STFactory.PerLocaleData.reviseInheritanceAsNeeded

-New unit test TestVoteResolver.testReviseInheritance for VoteResolver.reviseInheritanceAsNeeded

-Remove DataPage.DataRow.inheritsFromRootOrFallback, no longer necessary or appropriate

-Make isBaselineValue true for inheritance marker in DataPage.DataRow.addItem when appropriate to display star

-Comments

CLDR-16560

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2023-05-03 15:11 UTC, btangmu commented
This PR is similar to the earlier draft PR https://github.com/unicode-org/cldr/pull/2880 and fixes problems described in comments there

2023-05-03 20:49 UTC, srl295 submitted a review, later dismissed

2023-05-04 13:32 UTC, btangmu commented
@srl295 thanks for the review!

@macchiati @pedberg-icu this is a major change since it entails making DROP_HARD_INHERITANCE true again, so I'll wait so you have some more time to review.

This possibly finishes revision of inheritance for v44, unless you see problems with the PR, or problems arise after it's merged.

2023-05-04 15:02 UTC, macchiati requested changes

2023-05-04 21:06 UTC, btangmu commented on tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
> +    public static String reviseInheritanceAsNeeded(String path, String value, CLDRFile cldrFile) {
@macchiati I've added a unit test

2023-05-04 22:20 UTC, macchiati approved these changes

2023-05-05 00:17 UTC, merged