CLDR-16994 BRS: en_001 promotion
unicode-org/cldr pull request #3198
Opened 2023-08-17 17:43 UTC by srl295

CLDR-16994

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2023-08-17 18:08 UTC, srl295 commented
All done except the three 'maybes' - not sure what the final is on these.

2023-08-17 18:09 UTC, srl295 commented on common/annotations/en_001.xml
> +
later CLDRModify will reorder these.

2023-08-17 18:29 UTC, srl295 commented
> build: tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java#L192
(TestAnnotations.java:192) Error: : keywords for 👨‍⚖: expected java.util.HashSet<[scales, justice, man, judge]>, got com.google.common.collect.RegularImmutableSet<[judge, justice, law, man, scales]>

So… @macchiati what is this test checking?  Should en.xml not be changed here?

2023-08-17 20:16 UTC, macchiati requested changes
Hold off a bit until I find out about wi-fi

2023-08-21 21:01 UTC, srl295 commented
@macchiati  ping any update on `wifi`?

2023-08-21 21:18 UTC, srl295 commented
@macchiati test seems to just have hard coded values, i've updated them

2023-08-22 03:22 UTC, macchiati approved these changes

2023-08-22 14:25 UTC, merged

2023-08-22 14:26 UTC, srl295 commented
> @macchiati test seems to just have hard coded values, i've updated them

Does the golden test case here add value? If it's testing parsing, would it be better to just start with a static extract from English instead of running against live data?