CLDR-17133 CLDRModify -fQ. update annotations from TTS name, some ann…
unicode-org/cldr pull request #3292
Opened 2023-09-29 22:34 UTC by DraganBesevic

…otations got improperly merged

CLDR-17133

- [x] This PR completes the ticket.

CLDRModify no arguments

No changes

CLDRModify -fQ

Updated TTS names to annotations to remove the superfluous entries

CLDRModify -fP

No changes

ALLOW_MANY_COMMITS=true

2023-09-29 22:49 UTC, pedberg-icu requested changes
This still has the problem of removing the draft="unconfirmed" status for the regular entry when both the regular and tts entries have draft="unconfirmed". That is non-starter. will check with Tom.

2023-10-03 19:29 UTC, pedberg-icu approved these changes

2023-10-03 19:51 UTC, merged

2023-10-03 20:22 UTC, btangmu commented on common/annotations/bew.xml
> +		<annotation cp="😄">girang | ketawa | mata ketutup | muka | muka girang mata ketutup | seneng</annotation>
@DraganBesevic @pedberg-icu I think I see why this happens: `CLDRModify.CLDRFilter.replace` is supposed to be called with `fullpath` not just the path gotten by looping through the CLDRFile

2023-10-03 20:55 UTC, pedberg-icu commented
> This still has the problem of removing the draft="unconfirmed" status for the regular entry when both the regular and tts entries have draft="unconfirmed". That is non-starter. will check with Tom.

Fixed that manually before merging.

2023-10-03 21:02 UTC, btangmu commented on common/annotations/bew.xml
> +		<annotation cp="😄">girang | ketawa | mata ketutup | muka | muka girang mata ketutup | seneng</annotation>
https://github.com/unicode-org/cldr/pull/3307