CLDR-11982 lv collation
unicode-org/cldr pull request #3425
Opened 2023-12-27 20:29 UTC by Mazurs

Use the collation rules described in the LVS 24:1993 standard.

CLDR-11982

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2023-12-27 22:53 UTC, srl295 reviewed
structure lgtm

2023-12-27 22:54 UTC, srl295 commented
@Mazurs thanks for creating this (and signing CLA!) — i'll kick off the autotests, meanwhile @markusicu can review…

2023-12-31 03:10 UTC, srl295 commented
@Mazurs looks like it passes tests.  give us some time to take a look, but this seems like it should be on it way to merging.

2024-01-26 20:16 UTC, markusicu requested changes
the order looks like the provided translated reference

please change the reference in the data file

2024-01-26 20:16 UTC, markusicu commented on common/collation/lv.xml
>  			<collation type="standard" references="Dzintra Kalniņa: Latvian-English Dictionary ISBN 9984-700-52-6">
```suggestion
			<collation type="standard" references="LVS 24:1993, LATVIAN LANGUAGE SUPPORT FOR COMPUTERS">
```

2024-01-28 00:53 UTC, markusicu reviewed
The changes all look good now, but the second commit is missing the `CLDR-11982 ` prefix, and that blocks merging the PR.

Please
- either squash the commits and use just the first commit message
- or amend the second commit, adding the prefix to the commit message (and I can then squash-and-merge)

2024-01-29 20:21 UTC, Mazurs commented
Made another pull request with merged commits: #3469

2024-01-29 20:49 UTC, markusicu commented
> Made another pull request with merged commits: #3469

Ok... you could have just amended or squashed this one... doesn't really matter, I approved the new one and will merge if the tests are happy.

2024-01-29 20:49 UTC, closed without merging