CLDR-17416 v45 BRS validity
unicode-org/cldr pull request #3531
Opened 2024-02-27 21:18 UTC by srl295

- also note we are starting to see spdx changes from CLDR-17110

CLDR-17416

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2024-02-27 23:31 UTC, macchiati commented
Tests failing

2024-02-28 00:34 UTC, srl295 commented on common/validity/script.xml
> -			Yezi Yiii Zanb
what's going on with `Zanb`? @markusicu @macchiati

2024-02-28 00:37 UTC, srl295 commented on common/validity/script.xml
> -			Yezi Yiii Zanb
We've been here before.. https://github.com/unicode-org/cldr/pull/3233#issuecomment-1701848571 

blocked by CLDR-17056  - I'll back out `Zanb` for now.

2024-02-28 00:40 UTC, srl295 commented on common/validity/script.xml
> +			Yezi Yiii Zanb <!-- Note: for Zanb see CLDR-17056 -->
^ so that we see this the next time the generator is run

2024-02-28 05:20 UTC, macchiati requested changes
I decided it was time to fix the tooling. I figured that rather than have the tooling be a separate PR, it was better to do it all at once. So could you review https://github.com/unicode-org/cldr/pull/3537 and if that's ok, merge it and close this PR?

2024-02-29 20:18 UTC, closed without merging