CLDR-17514 Pages too big (v46): further divisions for Volume, Units
unicode-org/cldr pull request #3614
Opened 2024-04-05 15:31 UTC by btangmu

-Divide Volume Other into Volume US and Volume Other

-Divide Other Units into Other Units Metric, Other Units Metric Per, Other Units US and Other Units

-New subroutines getOtherUnitsPageId, isSystemUnit, getShortUnitId

-Fix deprecation warnings: remove getSectionsToPages; fix TestZ and filterCldr

CLDR-17514

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2024-04-05 15:36 UTC, btangmu commented
This doesn't complete the ticket; there are more large pages to divide. Also, the names of the divided pages, and the criteria for dividing them, are open to improvement. I suggest we merge this PR anyway as another step in the right direction.

2024-04-09 17:29 UTC, srl295 requested changes
typo?

2024-04-09 17:29 UTC, srl295 commented on tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
> +        OtherUnitsMetric(SectionId.Units, "Other Unitsj Metric"),
```suggestion
        OtherUnitsMetric(SectionId.Units, "Other Units Metric"),
```

typo?

2024-04-09 17:42 UTC, srl295 approved these changes

2024-04-10 14:40 UTC, merged