CLDR-17416 v45 brs: spec link check
unicode-org/cldr pull request #3634
Opened 2024-04-15 17:34 UTC by srl295

- linguistics-ontology.org/gold is no longer available, changed to archive.org links
- other fixes

CLDR-17416

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2024-04-15 18:28 UTC, pedberg-icu submitted a review, later dismissed

2024-04-15 21:38 UTC, AEApple submitted a review, later dismissed

2024-04-15 22:31 UTC, macchiati requested changes

2024-04-15 22:31 UTC, macchiati commented on docs/ldml/tr35-general.md
> +(adapted from: [linguistics-ontology.org/gold/2010/GenderProperty](https://web.archive.org/20200115041525/linguistics-ontology.org/gold/2010/GenderProperty) - links below go to an archived version. T
The message sounds like someone can go to <https://linguistlist.org/gold/> for the data, which isn't true.

```suggestion
(adapted from: [linguistics-ontology.org/gold/2010/GenderProperty](https://web.archive.org/20200115041525/linguistics-ontology.org/gold/2010/GenderProperty) - the links below go to an archived version. The original site is no longer available, as explained at <https://linguistlist.org/gold/>.)
```

2024-04-15 22:35 UTC, macchiati reviewed
Other than that, seems good. Was this the w3c link checker?

2024-04-15 22:40 UTC, macchiati commented
Hmmm. I just ran the w3c linkchecker on the main file, and it had some additional problems:

error Line: 1009 https://www.unicode.org/reports/tr35/tr35-72/tr35.html
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 5380 https://cldr-smoke.unicode.org/spec/main/ldml/unit-prefixes
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1033 https://www.unicode.org/cldr/dtd/45/
Status: 302 -> 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 5200 https://www.iso.org/obp/ui/
Status: 200 (no message)
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://www.iso.org/obp/ui/#search (line 5200)
info Line: 1001 mailto:markdavis@google.com
Status: (N/A) Access to 'mailto' URIs has been disabled
Accessing links with this URI scheme has been disabled in link checker.

2024-04-15 22:49 UTC, srl295 commented
> Other than that, seems good. Was this the w3c link checker?

no, lychee

2024-04-15 22:51 UTC, srl295 commented
> Hmmm. I just ran the w3c linkchecker on the main file, and it had some additional problems:
> 
> error Line: 1009 https://www.unicode.org/reports/tr35/tr35-72/tr35.html Status: 404 Not Found The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

this one will exist when we publish

> 
> error Line: 5380 https://cldr-smoke.unicode.org/spec/main/ldml/unit-prefixes Status: 404 Not Found The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

fixed in this PR


> error Line: 1033 https://www.unicode.org/cldr/dtd/45/ Status: 302 -> 404 Not Found The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

will exist when we publish

> 
> error Line: 5200 https://www.iso.org/obp/ui/ Status: 200 (no message) Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

this is a link to a resource with in the SPA, the page loads fine

> 
> Broken fragments: https://www.iso.org/obp/ui/#search (line 5200) info Line: 1001 [mailto:markdavis@google.com](mailto:markdavis@google.com) Status: (N/A) Access to 'mailto' URIs has been disabled Accessing links with this URI scheme has been disabled in link checker.

will have to email them to see if that link works!

2024-04-16 00:03 UTC, srl295 commented
Can i get a re review?

2024-04-16 01:19 UTC, macchiati commented
By the following comment:
> this one will exist when we publish
do you mean:
> this one will be **fixed** once we publish

2024-04-16 01:20 UTC, macchiati approved these changes

2024-04-16 01:21 UTC, merged

2024-04-16 04:28 UTC, srl295 commented
> By the following comment:
> 
> > this one will exist when we publish
> 
> do you mean:
> 
> > this one will be **fixed** once we publish

The resource identified by the url will exist when we publish.