CLDR-17812 v46 vxml: Add {0} for de speed-light-speed one, fix error wording in TestCheckCLDR/TestPlaceholders
unicode-org/cldr pull request #3887
Opened 2024-07-18 22:28 UTC by pedberg-icu

CLDR-17812

- [ ] This PR completes the ticket.

merge into [#3880](https://github.com/unicode-org/cldr/pull/3880)

`de` added unit data for speed-light-speed in which the "one" case has no placeholder; per discussion that reflects a misunderstanding of how this data is intended to be used, so add a placeholder so tests pass (the data will be deleted soon anyway). Also fix the wording of an error message in TestCheckCLDR/TestPlaceholders.

ALLOW_MANY_COMMITS=true

2024-07-18 22:49 UTC, macchiati requested changes
Thanks for taking this. I think the solution is a bit different.

The LOCALE_DEPENDENT path means that there is an extra test on the locale's plural rules to make sure that it behaves like Arabic (and other languages); that is, where a particular plural form is unique and therefore does not need a placeholder. For example, "1 book" in Arabic is just "كتاب".

So for this case, the error message is misleading, and the German should be fixed to prefix the values with 
"{0} "

2024-07-18 23:17 UTC, pedberg-icu commented
> Thanks for taking this. I think the solution is a bit different.
> ...
> So for this case, the error message is misleading, and the German should be fixed to prefix the values with "{0} "

@macchiati Hmm. What German currently has is
- one: Lichtgeschwindigkeit = Speed of light
- other: {0}-fache Lichtgeschwindigkeit = {0} times the speed of light

That seems very sensible to me. Saying "1 times the speed of light" is certainly awkward in English and I would think in German too. The particle is traveling at lightspeeed, or the particle is traveling at 0.3 times the speed of light.

2024-07-19 01:30 UTC, macchiati commented
I think there are significant issues with the data for a number of locales (will outline in email), so we probably want to retract the data for light-speed across locales. However, I suggest that we have a quick fix to the data and merge it into main before retracting so that we have a copy we can return to as needed.

So the quick fix I'm proposing is to add {0} before Lichtgeschwindigkeit

2024-07-19 01:36 UTC, pedberg-icu commented
> So the quick fix I'm proposing is to add {0} before Lichtgeschwindigkeit

Literally just "{0}" before, or "{0}-fache" before as with the `other` case?

2024-07-19 01:39 UTC, macchiati commented
Just "{0} " before is fine (just sent you a note about the complexities).

On Thu, Jul 18, 2024 at 6:36 PM Peter Edberg ***@***.***>
wrote:

> So the quick fix I'm proposing is to add {0} before Lichtgeschwindigkeit
>
> Literally just "{0}" before, or "{0}-fache" before as with the other case?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/cldr/pull/3887#issuecomment-2237853865>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLEMBGMT66X7SMQ6CPKEDZNBUTJAVCNFSM6AAAAABLDQ3DPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMZXHA2TGOBWGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-19 02:10 UTC, pedberg-icu commented
@macchiati OK I think I fixed as requested, PTAL. The error message wording was still backwards, needed fixing (see the previous error message by viewing more context above).

2024-07-19 03:35 UTC, macchiati approved these changes

2024-07-19 16:04 UTC, srl295 approved these changes

2024-07-19 16:11 UTC, srl295 approved these changes

2024-07-19 16:35 UTC, merged