CLDR-17587 Add Haitian Creole
unicode-org/cldr pull request #3948
Opened 2024-08-08 16:06 UTC by conradarcturus

This adds core data for Haitian Creole so that in Fall 2024 / v47 we can fill out the information for this locale.

CLDR-17587

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2024-08-08 16:19 UTC, srl295 commented
Scheduling - this should target v47 and be merged *after* main is branched for v46

2024-08-15 15:59 UTC, srl295 requested changes
Generally LGTM though:
- [x] needs to wait for v47 - maybe better to keep this in draft until then?
- [x] the explicit parentage fr -> ht is allowed but the parent locale was not set in this PR yet
- [ ] need to run spotless to cleanup the code ( see the `tools/README.md#spotless` docs )

2024-09-16 18:57 UTC, conradarcturus commented
@srl295  are there still any changes that need to be made?

2024-10-25 17:48 UTC, srl295 approved these changes

2024-10-25 20:44 UTC, merged