CLDR-17751 add ZWG, drop ZWL
unicode-org/cldr pull request #3956
Opened 2024-08-13 21:27 UTC by srl295

- update ZWG per ISO amendment
- retain USD as valid due to feedback and articles
- update English

CLDR-17751

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2024-08-13 21:38 UTC, AEApple commented
Where is ZWG?

2024-08-13 21:38 UTC, macchiati commented
My thought too!

2024-08-13 21:44 UTC, macchiati approved these changes

2024-08-13 21:47 UTC, srl295 commented
> My thought too!

yea… missing something important!

2024-08-13 21:47 UTC, AEApple approved these changes

2024-08-13 21:56 UTC, AEApple commented
This actually looks wrong in staging? ZWL and ZWG don't appear properly split out. Also I expect ZWL to have a date range, but only one date is showing?

2024-08-13 23:47 UTC, macchiati commented
What are you seeing on staging?

(if there is no "to" value, that just means that there is no set 'termination' date. That's typically for the current currency valid for a country)

2024-08-13 23:52 UTC, roozbehp requested changes

2024-08-13 23:52 UTC, roozbehp commented on common/main/en.xml
> +				<displayName count="other">Zimbabwean Gold</displayName>
I think the cases for one and other should use a lowercase "gold".

2024-08-14 17:53 UTC, roozbehp approved these changes

2024-08-15 18:28 UTC, roozbehp approved these changes

2024-08-15 19:09 UTC, srl295 commented
@roozbehp appreciate your re-review. Github was down when I made the other, so i forgot that it was still in progress.

2024-08-15 19:42 UTC, srl295 commented
@macchiati got a null pointer in `en_Dsrt` - it was trying to compare it as a logical group

2024-08-15 20:16 UTC, srl295 commented
I found the issue. CountItems silently completed because I passed the -Dmethod parameter incorrectly. Noted this on https://unicode-org.atlassian.net/browse/CLDR-17555

2024-08-15 23:35 UTC, roozbehp approved these changes

2024-08-15 23:39 UTC, merged