CLDR-18008 Specify that currency digits might NOT be derived from ISO 4217
unicode-org/cldr pull request #4112
Opened 2024-10-07 02:19 UTC by sffc

CLDR-18008

- [x] This PR completes the ticket.

Alternative B. Compare to Alternative A: #4111

2024-10-07 17:28 UTC, macchiati requested changes

2024-10-07 17:28 UTC, macchiati commented on docs/ldml/tr35-numbers.md
> +* **digits:** the minimum and maximum number of decimal digits normally formatted. The default is 2. For example, in the en_US locale with the default value of 2 digits, the value 1 USD would format
```suggestion
* **digits:** the minimum and maximum number of decimal digits normally formatted. 
The default is 2. 
For example, in the en_US locale with the default value of 2 digits, the value 1 USD would format as "$1.00", and the value 1.123 USD would format as → "$1.12". 
This value of this field is based on the "minor unit" value from ISO 4217, but may deviate from ISO 4217 where there is compelling evidence for different customary practice.
```

2024-10-07 17:28 UTC, macchiati commented on docs/ldml/tr35-numbers.md
> +* **digits:** the minimum and maximum number of decimal digits normally formatted. The default is 2. For example, in the en_US locale with the default value of 2 digits, the value 1 USD would format
Reviewed in the design meeting. Note that the **usage** of currencies in countries may also deviate from ISO, based on customary practice.

2024-10-08 03:27 UTC, macchiati approved these changes

2024-10-08 04:19 UTC, sffc commented
I re-opened the issue because the PR hadn't been merged yet.

2024-10-08 05:52 UTC, merged