CLDR-18170 46.1 release page
unicode-org/cldr pull request #4236
Opened 2024-12-09 22:10 UTC by macchiati

CLDR-18170

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

2024-12-09 22:31 UTC, AEApple commented
Well the markdown table isn't rendering correctly, and shouldn't we say it's in Beta until we're ready to release it?

2024-12-09 22:55 UTC, macchiati commented
That was just a rough draft to get us started; I had a bunch of notes in a
different thread.

On Mon, Dec 9, 2024 at 2:31 PM Annemarie Apple ***@***.***>
wrote:

> Well the markdown table isn't rendering correctly in the preview, and
> shouldn't we say it's in Beta until we're ready to release it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/cldr/pull/4236#issuecomment-2529675036>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLEMGQQ3YAUKQIP7FPSIL2EYK4ZAVCNFSM6AAAAABTJZUBQCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRZGY3TKMBTGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-12-09 23:00 UTC, macchiati commented
1. Text is a rough draft
2. I put the 46.1 section right after the overview rather than at the bottom, to highlight better. 
    3. Maybe make the header "Release 46.1"?
4. Needs the most-significant MF2.0 items list from Addison
5. In the header, there is a new row for 46.1. 
    6. The links etc need fixing
    7. The release note link should be changed to the new section
    8. For the charts, we could either say n/a, or build 46.1 charts in the https://unicode.org/cldr/charts/46/ directory.
    9. The spec needs to be LDML46.1
    10. The delta is ok.
    11. The release needs to say/link 46.1
    12. The CLDR JSON needs to say/link to 46.1
    13. Once it is all done, the new row needs to be copied to https://cldr.unicode.org/index/downloads
    14. In https://e6182513.cldr.pages.dev/, the table at the top is not HTMLified. Not sure why

2024-12-09 23:05 UTC, pedberg-icu commented on docs/site/downloads/cldr-46.md
> +|  46.1 | 2024-12-18 | [v46.1](/index/downloads/cldr-46.1) | [CLDR46.1](https://unicode.org/Public/cldr/46.1/) | [Charts46.1](https://unicode.org/cldr/charts/46.1/) | [LDML46](https://www.unicode.org
index/downloads/cldr-46.1 is not the right link for a release note, we are just adding stuff into index/downloads/cldr-46. And are we planning to generate new charts for 46.1? And the spec will be version 74, not 73. And the release tag will be "release-46-1" (like the other dot releases), not 46.1

2024-12-09 23:05 UTC, pedberg-icu requested changes
See previous note about fixes

2024-12-09 23:06 UTC, pedberg-icu commented on docs/site/downloads/cldr-46.md
> +|  46.1 | 2024-12-18 | [v46.1](/index/downloads/cldr-46.1) | [CLDR46.1](https://unicode.org/Public/cldr/46.1/) | [Charts46.1](https://unicode.org/cldr/charts/46.1/) | [LDML46](https://www.unicode.org
And the entry for the json tag should have [46.1.0]

2024-12-11 05:02 UTC, AEApple commented
@pedberg-icu - should we just approve this and then make follow on changes since it would be good to have it updated for the beta until we finalize the release?

2024-12-11 16:41 UTC, pedberg-icu commented on docs/site/downloads/cldr-46.md
> +|  46.1 | 2024-12-18 | [v46.1](/index/downloads/cldr-46.1) | [CLDR46.1](https://unicode.org/Public/cldr/46.1/) | [Charts46.1](https://unicode.org/cldr/charts/46.1/) | [LDML46](https://www.unicode.org
Well, I will unblock this so we can merge and then make a separate PR to fix the issues noted above.

2024-12-11 16:42 UTC, pedberg-icu commented
> @pedberg-icu - should we just approve this and then make follow on changes since it would be good to have it updated for the beta until we finalize the release?

Yes

2024-12-11 16:45 UTC, pedberg-icu requested changes
Actually I will re-block. We cannot merge this as is, it will break the existing public release page for 46.

2024-12-11 16:48 UTC, closed without merging