CLDR-14297 update ICU4J libs version in tools/pom.xml
unicode-org/cldr pull request #848
Opened 2020-11-18 08:35 UTC by pedberg-icu

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14297
- [x] Updated PR title and link in previous line to include Issue number

2020-11-18 15:58 UTC, srl295 requested changes

2020-11-18 15:58 UTC, srl295 commented on tools/pom.xml
> +		<icu4j.version>68.1-release-68-1</icu4j.version>
```suggestion
		<icu4j.version>68.1-release-68-1</icu4j.version>
```

See the URL on line 19 - you can see the exact tag names. If you click one such as https://github.com/unicode-org/icu/packages/411079?version=68.1-release-68-1 you can see them in detail: `<version>68.1-release-68-1</version>`

2020-11-18 18:27 UTC, srl295 submitted a review, later dismissed
I think that the asset may just not have built when this ran.

2020-11-18 18:44 UTC, srl295 commented
I think I know what's going on here.

Since the PR is in _your fork_, Github actions does NOT supply the secrets that it would have if it was in the head fork.
Normally this asset would be cached, but since this is the first time it's seen 68.1 release, it doesn't work.

Update: no, that didn't fix it. hmm

2020-11-18 21:32 UTC, srl295 commented
@pedberg-icu you might need to rebase on top of https://github.com/unicode-org/cldr/pull/849 to get this to work

2020-11-18 22:35 UTC, srl295 commented
@pedberg-icu rebased branch in https://github.com/unicode-org/cldr/tree/CLDR-14297-update-ICU-libs-via-pom

2020-11-18 23:51 UTC, pedberg-icu commented
@srl295 , looks like you did the rebase but this is stil faialing, e.g. the cldr-mvn / build (push) log shows:
```
Error:  Failed to execute goal on project cldr-code: Could not resolve dependencies for project org.unicode.cldr:cldr-code:jar:39.0-SNAPSHOT: Failed to collect dependencies at com.ibm.icu:icu4j-for-cldr:jar:68.1-release-68-1: Failed to read artifact descriptor for com.ibm.icu:icu4j-for-cldr:jar:68.1-release-68-1: Could not transfer artifact com.ibm.icu:icu4j-for-cldr:pom:68.1-release-68-1 from/to github (https://maven.pkg.github.com/unicode-org/cldr): Transfer failed for https://maven.pkg.github.com/unicode-org/cldr/com/ibm/icu/icu4j-for-cldr/68.1-release-68-1/icu4j-for-cldr-68.1-release-68-1.pom 400 Bad Request -> [Help 1]
```

2020-11-18 23:57 UTC, srl295 commented
> @srl295 , looks like you did the rebase but this is stil failing, e.g. the cldr-mvn / build (push) log shows:
> 
> ```
> 
> Error:  Failed to execute goal on project cldr-code: Could not resolve dependencies for project org.unicode.cldr:cldr-code:jar:39.0-SNAPSHOT: Failed to collect dependencies at com.ibm.icu:icu4j-for-cldr:jar:68.1-release-68-1: Failed to read artifact descriptor for com.ibm.icu:icu4j-for-cldr:jar:68.1-release-68-1: Could not transfer artifact com.ibm.icu:icu4j-for-cldr:pom:68.1-release-68-1 from/to github (https://maven.pkg.github.com/unicode-org/cldr): Transfer failed for https://maven.pkg.github.com/unicode-org/cldr/com/ibm/icu/icu4j-for-cldr/68.1-release-68-1/icu4j-for-cldr-68.1-release-68-1.pom 400 Bad Request -> [Help 1]
> 
> ```

I didn't rebase your branch. But on my own branch it worked. So if you rebase it should be ok.

2020-11-19 14:28 UTC, srl295 approved these changes

2020-11-19 14:31 UTC, pedberg-icu commented
Great, thanks, the rebasing to pick up #849 does seems to have fixed things.

2020-11-19 14:31 UTC, merged